### ISSUE TITLE
Allocation of voting power on review comments

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/api#21]
- 7.41% of @steemhunt's voting power should be allocated to upvote the review comments (pros and cons)
- The voting power on them should be 1/n
- We gotta add an interface to approve the review comments too.

**Comment by sydneyitguy** [comment]
Adding an interface to approve the review comments is a bit difficult (as we don't save comments data on our side atm)

Easier way would be:
Making a blacklist - so abusers / spammers don't get upvote by Steemhunt voting bot.
