### ISSUE TITLE
Voting power wasted due to small voting weight

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/api#50]
```
{
  "percent": 287,
  "reputation": "19063653796706",
  "rshares": "1,885,282,771,215", (added comma for better readability)
  "time": "2018-08-03T15:14:33",
  "voter": "steemhunt",
  "weight": 449487
}
{
  "percent": 14,
  "reputation": "19067407042600",
  "rshares": "314,213,795,202",
  "time": "2018-08-03T16:07:00",
  "voter": "steemhunt",
  "weight": 561801
}
```

Note that percentage difference between the first and second is 20x, but the actual rewards difference was only 6x.

I confirmed that Steem Blockchain calculates VP usage with the percentage casted, but ROUND DOWN when the percentage is too small (Steem dev guys said it's around 2%), that makes 0.1% and 0.5% has no difference in rewards (it's more like 0.5% steps by observing our voting data).

We have few options to fix this issue:
1. Split account into multiple smaller ones - so vote with higher %
2. Decrease the number of votings (= higher % on each)
   a. stricter level
   b. randomize & cap number of votings
   c. aggregate all voting weights for each users and vote on one comment
   d. decrease the max comment voting cap per users

Option 1 takes too much effort as we may have to request all sponsors to remove their delegation and re-delegate them into some different accounts.

2-a. our level distribution is already kind of very strict: `[3936, 1318, 125, 93, 33, 9]`
2-b. from our past experiment, randomized votings de-motivate users a lot even tough the expected reward doesn't change
2-c. takes quite a lot of dev time + ppl might misunderstand like "why a comment got upvoted like $30 even though the hunt post itself only upvoted $2?)
2-d. will decrease the number of comments

This issue will be fixed on HF20 (probably released in a month) anyway, so I guess we better take a simpler temporary option with the least side-effects.

I guess that should be 2-d.
Reducing the max comment voting cap per user from 5 to 2-3 will be good enough.
- This doesn't affect on total reward a user receive because less votings means more voting weight per hunt / comments.
- This will change  the hunt / comment voting ratio from 33% to 23% (when max 3) or 16% (when max 2)

This method is not scalable though.
If we see like 2x DAU, situation will be the same or even worse.

For more mid-long term solution, 2-b should be also considered for both hunt / comment votings.
something like random 100 hunts + 100 comments
- potentially with a different probability depending on levels

**Comment by sydneyitguy** [comment]
After some thought.

This time, let's take options 2-a and 2-b without probability difference by levels

Voting cap: 100 Hunts + 200 Comments
Hunts;
- Max 1 hunt per user - RANDOMIZED total 100 hunts in total (will be capped by ranking, but it doesn't mean we vote until rank 100, only 50% of hunts made by minimum level 1 users, so ranking cap is more likely like 200)

Comments:
- Max 3 comments per user - RANDOMIZED total 200 comments in total (writing more comments, higher the chances to be picked full  3 comments)
- Influencers: max 5 comments with 1% (3 with additional level weight)
- Mods: All comments with flat 0.6% (3 with additional level weight)

We have 17 infs and 10 mods now, so their unit total will be 3 * (17 + 10) = 81
Total  comment voting unit = 281 * 0.1
Total hunt voting unit would be always = 100

When N is the number of verified & active posts for that day, and put 50 as average number of influencer comments, one voting units will be:
```
weight_per_unit = (900 - 0.5 * 50 (inf comments) - 0.6 * N) / (1000 + 281)

- When N = 200 => (900 - 25 - 120)/1281 = 0.59
- When N = 400 => (900 - 25 - 240)/1281 = 0.49

This calculation doesn't include the level weight so there will be about 20-30% decrease in actual numbers
```

**Comment by cyh76507707** [comment]
My opinion:

[Daily Aggregated Upvotes]

Rules:
* All above-lv1-hunters are eligible to get upvotes max **1 hunting post and 3 comments** based on his/her hunter level.
* Steemhunt's upvotes will be aggregated on the hunting post, or the first comment when the hunter has no any hunting post at the day.
* After the midnight, bot will read all contents generated by each hunter and calculate voting weight units of the hunter.

Upvote comments:
* On each hunter's content, Steemhunt will leave an upvote report for transparency as below
* "Congratulations! You have received aggregated upvotes based on your hunter level by Steemhunt for your [hunt_count] hunting post and [hunter_comment_count] comments for your contributions on the community.
* For influencers: ""Congratulations! You have received aggregated upvotes based on your hunter level by Steemhunt for your [hunt_count] hunting post, [hunter_comment_count] comments, and [influencer_comment+count] influencer comments for your contributions on the community.
* For mod: ""Congratulations! You have received aggregated upvotes based on your hunter level by Steemhunt for your [hunt_count] hunting post, [hunter_comment_count] comments, and [mod_comment+count] moderator comments for your contributions on the community.

Benefits:
* It will reduce the number of Steemhunt upvotes.
* The report comment will solve the argument issue ("why this comment has higher upvote than my hunting post??")
* Easy to count real `active hunters` on our platform (number or upvotes = number of daily active hunters]
* Before HF20, we can still cover the scalability issue (after the issue will be fixed, we don't need to worry about the small percentage upvotes anyway).

**Comment by sydneyitguy** [comment]
Final decision:

- Max 100 votes on hunts
- Reduce max cap comments 5 to 3
- Reduce max cap inf comments 10 to 5

Less number of content, More weight - for now.
This ticket may be re-opened once we hit like 1000 unique users comment on the platform.

**Comment by sydneyitguy** [comment]
will be fixe don HF20
